import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'

const LLM_API_KEY = Deno.env.get('LLM_API_KEY') || ''
const LLM_ENDPOINT = Deno.env.get('LLM_ENDPOINT') || 'https://openrouter.ai/api/v1/chat/completions'
const LLM_MODEL = Deno.env.get('LLM_PUBLIC_MODEL') || Deno.env.get('LLM_MODEL') || 'google/gemini-2.5-flash'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-forwarded-for',
}

const ipRateLimit = new Map<string, number[]>()
const HOUR_MS = 60 * 60 * 1000
const MAX_REQUESTS_PER_HOUR = 5

function cleanupAndCheckRateLimit(ip: string) {
  const now = Date.now()
  const existing = ipRateLimit.get(ip) || []
  const fresh = existing.filter((timestamp) => now - timestamp < HOUR_MS)
  if (fresh.length >= MAX_REQUESTS_PER_HOUR) {
    ipRateLimit.set(ip, fresh)
    return false
  }
  fresh.push(now)
  ipRateLimit.set(ip, fresh)
  return true
}

function asArray(value: unknown) {
  return Array.isArray(value) ? value : []
}

function asString(value: unknown, fallback = '') {
  return typeof value === 'string' ? value : fallback
}

function asNumber(value: unknown, fallback = 0) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function normalizeIngredientGroup(group: any) {
  return {
    label: typeof group?.label === 'string' && group.label.trim() ? group.label.trim() : null,
    ingredients: asArray(group?.ingredients).map((ingredient: any) => ({
      amount: asString(ingredient?.amount, ''),
      unit: asString(ingredient?.unit, ''),
      item: asString(ingredient?.item, ''),
      note: typeof ingredient?.note === 'string' ? ingredient.note : undefined,
      optional: Boolean(ingredient?.optional),
    })).filter((ingredient: any) => ingredient.item),
  }
}

function normalizeInstructionGroup(group: any) {
  return {
    label: typeof group?.label === 'string' && group.label.trim() ? group.label.trim() : null,
    steps: asArray(group?.steps).map((step: any) => ({
      text: typeof step === 'string' ? step : asString(step?.text, ''),
      tip: typeof step?.tip === 'string' ? step.tip : undefined,
    })).filter((step: any) => step.text),
  }
}

function normalizeRecipe(recipe: any) {
  const ingredientGroups = asArray(recipe?.ingredientGroups).map(normalizeIngredientGroup).filter((group: any) => group.ingredients.length > 0)
  const instructionGroups = asArray(recipe?.instructionGroups).map(normalizeInstructionGroup).filter((group: any) => group.steps.length > 0)

  return {
    title: asString(recipe?.title, 'Generated recipe'),
    slug: asString(recipe?.slug, ''),
    description: asString(recipe?.description, ''),
    yield: asString(recipe?.yield, recipe?.servings ? `${recipe.servings} servings` : ''),
    prepTime: asNumber(recipe?.prepTime, 0),
    cookTime: asNumber(recipe?.cookTime, 0),
    totalTime: asNumber(recipe?.totalTime, asNumber(recipe?.prepTime, 0) + asNumber(recipe?.cookTime, 0)),
    difficulty: ['easy', 'medium', 'advanced'].includes(recipe?.difficulty) ? recipe.difficulty : 'medium',
    servings: Math.max(1, asNumber(recipe?.servings, 2)),
    ingredientGroups,
    instructionGroups,
    tips: asArray(recipe?.tips).filter((tip) => typeof tip === 'string'),
    substitutions: asArray(recipe?.substitutions).map((sub: any) => ({
      original: asString(sub?.original, ''),
      substitute: asString(sub?.substitute, ''),
      note: typeof sub?.note === 'string' ? sub.note : undefined,
    })).filter((sub: any) => sub.original && sub.substitute),
    tags: {
      cuisine: asString(recipe?.tags?.cuisine, ''),
      mealType: asString(recipe?.tags?.mealType, 'dinner'),
      dietary: asArray(recipe?.tags?.dietary).filter((value) => typeof value === 'string'),
      season: typeof recipe?.tags?.season === 'string' ? recipe.tags.season : undefined,
      cookingMethod: asArray(recipe?.tags?.cookingMethod).filter((value) => typeof value === 'string'),
    },
    nutrition: recipe?.nutrition && typeof recipe.nutrition === 'object'
      ? {
          calories: asNumber(recipe.nutrition.calories, 0),
          protein: asString(recipe.nutrition.protein, ''),
          carbs: asString(recipe.nutrition.carbs, ''),
          fat: asString(recipe.nutrition.fat, ''),
          fiber: typeof recipe.nutrition.fiber === 'string' ? recipe.nutrition.fiber : undefined,
          sodium: typeof recipe.nutrition.sodium === 'string' ? recipe.nutrition.sodium : undefined,
        }
      : undefined,
    sourceNote: typeof recipe?.sourceNote === 'string' ? recipe.sourceNote : 'Generated by Allio public meal generator.',
    imagePrompt: typeof recipe?.imagePrompt === 'string' ? recipe.imagePrompt : undefined,
  }
}

function validateRecipe(recipe: any) {
  if (!recipe.title || !recipe.description) return 'Missing title or description'
  if (!recipe.ingredientGroups?.length) return 'Missing ingredient groups'
  if (!recipe.instructionGroups?.length) return 'Missing instruction groups'
  const ingredientCount = recipe.ingredientGroups.flatMap((group: any) => group.ingredients).length
  const stepCount = recipe.instructionGroups.flatMap((group: any) => group.steps).length
  if (ingredientCount < 5) return 'Too few ingredients'
  if (stepCount < 4) return 'Too few steps'
  return null
}

function buildPrompt(payload: any) {
  const dietary = asArray(payload?.dietary).join(', ') || 'none'
  const allergies = asString(payload?.allergies, 'none')
  const audience = asString(payload?.audience, 'adults')
  const timeConstraint = asString(payload?.timeConstraint, '30')
  const mood = asString(payload?.mood, 'savory')
  const ingredients = asString(payload?.ingredients, '').trim()
  const servings = asString(payload?.servings, '2')
  const kidFriendly = audience.toLowerCase().includes('kid')

  return `You are a professional recipe developer. You write recipes for home cooks that are tested, precise, and actually delicious. You have deep knowledge of how ingredients behave under heat, how flavors build, and what makes a dish come alive.

COOKING PRINCIPLES, follow these in every recipe:

SEASONING:
- Protein must always be seasoned before cooking. At minimum salt and pepper. Often a light marinade or dry rub.
- Season in layers throughout cooking, not all at the end.
- Quantities must be realistic. A stir-fry for 4 needs at least 2 to 3 tablespoons of soy sauce, not 1 teaspoon.
- Include acid (citrus, vinegar) to brighten dishes. Most home cooks under-acid their food.

HEAT AND TIMING:
- Specify heat levels precisely: medium-high, not just "heat the pan."
- Include sensory cues: "until the onions are translucent and softened" or "until the garlic is fragrant, about 30 seconds."
- Include visual or sound cues: "you should hear an aggressive sizzle when the chicken hits the pan."
- Never say "until done." Always give temperature, visual cue, or time range.

INGREDIENT HANDLING:
- Fresh fruit in hot dishes should be added at the very end (last 30 seconds) or served raw on top as a garnish. Mango, pineapple, berries, they break down fast under heat.
- Herbs: hardy herbs (rosemary, thyme) go in early. Delicate herbs (basil, chives, cilantro) are stirred in at the end or used as garnish.
- Aromatics (garlic, ginger) burn fast over high heat. Add them after other ingredients have started cooking, or use medium heat. Never first into a screaming hot wok.
- Mushrooms need space and time to brown. Crowding steams them.

STRUCTURE:
- Mise en place matters. If marinating or pre-mixing a sauce, make that Step 1.
- Group related prep: "While the rice cooks, prepare the sauce" saves time and reads naturally.
- A good stir-fry has a sauce mixed in advance (soy, acid, sweetener, starch slurry) added all at once, not ingredient by ingredient.

TIPS:
- Never state the obvious ("don't burn the garlic," "don't overcrowd the pan").
- Good tips teach something: "Velveting the chicken in a cornstarch slurry before cooking keeps it silky and tender, a technique borrowed from Chinese restaurant kitchens."
- Include make-ahead, storage, and reheating instructions.
- Include one "if you have time" upgrade: a quick pickle, a toasted nut garnish, a compound butter.

DESCRIPTIONS:
- 2 to 3 sentences that tell the cook what to expect and why this recipe works.
- Never use filler like "you'll wonder why you haven't tried this before."
- Be specific: "The sauce caramelizes against the seared chicken, creating sticky-sweet edges that contrast with the bright crunch of raw mango on top."

COMPLETENESS:
- Every single ingredient mentioned in the instructions MUST appear in the ingredients list with a specific amount.
- This includes: cooking oil, salt, pepper, sauces, starches, garnishes, marinades, everything.
- Before finalizing, cross-check: scan every instruction step. If an ingredient is mentioned, confirm it exists in ingredientGroups with an amount and unit.
- The ingredients list is a shopping list. If someone bought only what's listed, they must be able to make the entire recipe with no surprises.

HARD REQUIREMENTS:
- The recipe must primarily use these ingredients: ${ingredients}
- Servings: ${servings}
- Dietary constraints: ${dietary}
- Allergies to avoid completely: ${allergies}
- Audience: ${audience}
- Time constraint: ${timeConstraint} minutes total
- Desired mood: ${mood}
- ${kidFriendly ? 'Kid-friendly is required. Favor familiar flavors, avoid heat, and keep textures approachable.' : 'This recipe is for adults unless constraints say otherwise.'}

OUTPUT FORMAT:
Return valid JSON matching this exact structure:
{
 "title": "string",
 "slug": "string (kebab-case)",
 "description": "string (2-3 sentences, evocative and specific)",
 "yield": "string",
 "prepTime": number,
 "cookTime": number,
 "totalTime": number,
 "difficulty": "easy|medium|advanced",
 "ingredientGroups": [
 {
 "label": "string or null",
 "ingredients": [
 {
 "amount": "string (use fractions: 1½ not 1.5)",
 "unit": "string",
 "item": "string (always include prep: finely diced, minced, etc.)",
 "note": "string or null (substitution note)",
 "optional": boolean
 }

CRITICAL INGREDIENT FORMATTING RULE:
- The "unit" field contains ONLY the unit: "pound", "cup", "tablespoon", "teaspoon", "clove", "ounce"
- The "item" field must NOT repeat the unit. It contains only the ingredient and prep.
- WRONG: { "amount": "2", "unit": "cups", "item": "cups cherry tomatoes, halved" }
- RIGHT: { "amount": "2", "unit": "cups", "item": "cherry tomatoes, halved" }
- WRONG: { "amount": "2", "unit": "cloves", "item": "cloves garlic, minced" }
- RIGHT: { "amount": "2", "unit": "cloves", "item": "garlic, minced" }
 ]
 }
 ],
 "instructionGroups": [
 {
 "label": "string or null",
 "steps": [
 {
 "text": "string (full instruction with sensory cues and timing)",
 "tip": "string or null (only if genuinely useful)"
 }
 ]
 }
 ],
 "tips": ["string"],
 "substitutions": [
 {
 "original": "string",
 "substitute": "string",
 "note": "string or null"
 }
 ],
 "tags": {
 "cuisine": "string",
 "mealType": "dinner",
 "dietary": ["string"],
 "season": "string or null",
 "cookingMethod": ["string"]
 },
 "nutrition": {
 "calories": number,
 "protein": "string",
 "carbs": "string",
 "fat": "string",
 "fiber": "string or null",
 "sodium": "string or null"
 },
 "sourceNote": "string",
 "imagePrompt": "string"
}

Return JSON only. No markdown. No explanation.`
}

async function callLlm(messages: Array<{ role: string; content: string }>) {
  const response = await fetch(LLM_ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${LLM_API_KEY}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://allio.life',
      'X-Title': 'Allio Public Meal Generator',
    },
    body: JSON.stringify({
      model: LLM_MODEL,
      messages,
      response_format: { type: 'json_object' },
      temperature: 0.8,
    }),
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`OpenRouter error ${response.status}: ${text}`)
  }

  return await response.json()
}

function extractLlmContent(llm: any) {
  const content = llm?.choices?.[0]?.message?.content
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    const text = content
      .map((part) => typeof part?.text === 'string' ? part.text : '')
      .join('')
      .trim()
    if (text) return text
  }
  return ''
}

async function generateRecipe(payload: any) {
  const systemPrompt = buildPrompt(payload)
  const baseMessages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: 'Generate one recipe now.' },
  ]

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const llm = await callLlm(baseMessages)
    const content = extractLlmContent(llm)
    if (!content) throw new Error('LLM returned empty content')

    try {
      const parsed = JSON.parse(content)
      const normalized = normalizeRecipe(parsed)
      const validationError = validateRecipe(normalized)
      if (!validationError) return normalized

      if (attempt === 0) {
        baseMessages.push({
          role: 'user',
          content: `Your previous response was malformed: ${validationError}. Return corrected JSON only, preserving all requested fields.`,
        })
        continue
      }
      throw new Error(validationError)
    } catch (error) {
      if (attempt === 0) {
        baseMessages.push({
          role: 'user',
          content: 'Your previous response was malformed JSON. Return corrected JSON only, with the exact requested schema.',
        })
        continue
      }
      throw error
    }
  }

  throw new Error('Unable to generate recipe')
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  const forwardedFor = req.headers.get('x-forwarded-for') || 'unknown'
  const ip = forwardedFor.split(',')[0].trim() || 'unknown'
  if (!cleanupAndCheckRateLimit(ip)) {
    return new Response(JSON.stringify({ error: 'Too many requests. Please wait a bit and try again.' }), {
      status: 429,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  try {
    if (!LLM_API_KEY) {
      return new Response(JSON.stringify({
        ok: false,
        error: 'Public meal generator is not configured yet. Missing LLM API key.',
      }), {
        status: 503,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const payload = await req.json()
    const recipe = await generateRecipe(payload)

    return new Response(JSON.stringify({ ok: true, recipe }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    console.error('[generate-public-meal] error', error?.message || error)
    return new Response(JSON.stringify({
      ok: false,
      error: 'Sorry, I could not generate a polished recipe right now. Please try again in a moment.',
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
