import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'

const LLM_API_KEY = Deno.env.get('LLM_API_KEY') || ''
const LLM_ENDPOINT = Deno.env.get('LLM_ENDPOINT') || 'https://openrouter.ai/api/v1/chat/completions'
const LLM_MODEL = Deno.env.get('LLM_PUBLIC_MODEL') || Deno.env.get('LLM_MODEL') || 'google/gemini-2.5-flash-preview'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-forwarded-for',
}

const ipRateLimit = new Map<string, number[]>()
const HOUR_MS = 60 * 60 * 1000
const MAX_REQUESTS_PER_HOUR = 5

function cleanupAndCheckRateLimit(ip: string) {
  const now = Date.now()
  const existing = ipRateLimit.get(ip) || []
  const fresh = existing.filter((timestamp) => now - timestamp < HOUR_MS)
  if (fresh.length >= MAX_REQUESTS_PER_HOUR) {
    ipRateLimit.set(ip, fresh)
    return false
  }
  fresh.push(now)
  ipRateLimit.set(ip, fresh)
  return true
}

function asArray(value: unknown) {
  return Array.isArray(value) ? value : []
}

function asString(value: unknown, fallback = '') {
  return typeof value === 'string' ? value : fallback
}

function asNumber(value: unknown, fallback = 0) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function normalizeIngredientGroup(group: any) {
  return {
    label: typeof group?.label === 'string' && group.label.trim() ? group.label.trim() : null,
    ingredients: asArray(group?.ingredients).map((ingredient: any) => ({
      amount: asString(ingredient?.amount, ''),
      unit: asString(ingredient?.unit, ''),
      item: asString(ingredient?.item, ''),
      note: typeof ingredient?.note === 'string' ? ingredient.note : undefined,
      optional: Boolean(ingredient?.optional),
    })).filter((ingredient: any) => ingredient.item),
  }
}

function normalizeInstructionGroup(group: any) {
  return {
    label: typeof group?.label === 'string' && group.label.trim() ? group.label.trim() : null,
    steps: asArray(group?.steps).map((step: any) => ({
      text: typeof step === 'string' ? step : asString(step?.text, ''),
      tip: typeof step?.tip === 'string' ? step.tip : undefined,
    })).filter((step: any) => step.text),
  }
}

function normalizeRecipe(recipe: any) {
  const ingredientGroups = asArray(recipe?.ingredientGroups).map(normalizeIngredientGroup).filter((group: any) => group.ingredients.length > 0)
  const instructionGroups = asArray(recipe?.instructionGroups).map(normalizeInstructionGroup).filter((group: any) => group.steps.length > 0)

  return {
    title: asString(recipe?.title, 'Generated recipe'),
    slug: asString(recipe?.slug, ''),
    description: asString(recipe?.description, ''),
    yield: asString(recipe?.yield, recipe?.servings ? `${recipe.servings} servings` : ''),
    prepTime: asNumber(recipe?.prepTime, 0),
    cookTime: asNumber(recipe?.cookTime, 0),
    totalTime: asNumber(recipe?.totalTime, asNumber(recipe?.prepTime, 0) + asNumber(recipe?.cookTime, 0)),
    difficulty: ['easy', 'medium', 'advanced'].includes(recipe?.difficulty) ? recipe.difficulty : 'medium',
    servings: Math.max(1, asNumber(recipe?.servings, 2)),
    ingredientGroups,
    instructionGroups,
    tips: asArray(recipe?.tips).filter((tip) => typeof tip === 'string'),
    substitutions: asArray(recipe?.substitutions).map((sub: any) => ({
      original: asString(sub?.original, ''),
      substitute: asString(sub?.substitute, ''),
      note: typeof sub?.note === 'string' ? sub.note : undefined,
    })).filter((sub: any) => sub.original && sub.substitute),
    tags: {
      cuisine: asString(recipe?.tags?.cuisine, ''),
      mealType: asString(recipe?.tags?.mealType, 'dinner'),
      dietary: asArray(recipe?.tags?.dietary).filter((value) => typeof value === 'string'),
      season: typeof recipe?.tags?.season === 'string' ? recipe.tags.season : undefined,
      cookingMethod: asArray(recipe?.tags?.cookingMethod).filter((value) => typeof value === 'string'),
    },
    nutrition: recipe?.nutrition && typeof recipe.nutrition === 'object'
      ? {
          calories: asNumber(recipe.nutrition.calories, 0),
          protein: asString(recipe.nutrition.protein, ''),
          carbs: asString(recipe.nutrition.carbs, ''),
          fat: asString(recipe.nutrition.fat, ''),
          fiber: typeof recipe.nutrition.fiber === 'string' ? recipe.nutrition.fiber : undefined,
          sodium: typeof recipe.nutrition.sodium === 'string' ? recipe.nutrition.sodium : undefined,
        }
      : undefined,
    sourceNote: typeof recipe?.sourceNote === 'string' ? recipe.sourceNote : 'Generated by Allio public meal generator.',
    imagePrompt: typeof recipe?.imagePrompt === 'string' ? recipe.imagePrompt : undefined,
  }
}

function validateRecipe(recipe: any) {
  if (!recipe.title || !recipe.description) return 'Missing title or description'
  if (!recipe.ingredientGroups?.length) return 'Missing ingredient groups'
  if (!recipe.instructionGroups?.length) return 'Missing instruction groups'
  const ingredientCount = recipe.ingredientGroups.flatMap((group: any) => group.ingredients).length
  const stepCount = recipe.instructionGroups.flatMap((group: any) => group.steps).length
  if (ingredientCount < 5) return 'Too few ingredients'
  if (stepCount < 4) return 'Too few steps'
  return null
}

function buildPrompt(payload: any) {
  const dietary = asArray(payload?.dietary).join(', ') || 'none'
  const allergies = asString(payload?.allergies, 'none')
  const audience = asString(payload?.audience, 'adults')
  const timeConstraint = asString(payload?.timeConstraint, '30')
  const mood = asString(payload?.mood, 'savory')
  const ingredients = asString(payload?.ingredients, '').trim()
  const servings = asString(payload?.servings, '2')
  const kidFriendly = audience.toLowerCase().includes('kid')

  return `You are a top-tier recipe developer writing for a premium cooking product. Return exactly one recipe as valid JSON only.

HARD REQUIREMENTS:
- The recipe must primarily use these ingredients: ${ingredients}
- Servings: ${servings}
- Dietary constraints: ${dietary}
- Allergies to avoid completely: ${allergies}
- Audience: ${audience}
- Time constraint: ${timeConstraint} minutes total
- Desired mood: ${mood}
- ${kidFriendly ? 'Kid-friendly is required. Favor familiar flavors, avoid heat, and keep textures approachable.' : 'This recipe is for adults unless constraints say otherwise.'}

QUALITY BAR:
- NYT Cooking quality
- 2 to 3 sentence evocative description
- ingredients must include prep in the item field when relevant, for example: "4 cloves garlic, minced"
- steps must include timing and sensory cues, for example: "until deeply golden, 5 to 7 minutes"
- include truly useful tips, substitutions, and approximate nutrition

Return this exact JSON structure:
{
  "title": "...",
  "slug": "...",
  "description": "...",
  "yield": "...",
  "prepTime": 10,
  "cookTime": 20,
  "totalTime": 30,
  "difficulty": "easy",
  "servings": 2,
  "ingredientGroups": [
    {
      "label": null,
      "ingredients": [
        { "amount": "...", "unit": "...", "item": "...", "optional": false }
      ]
    }
  ],
  "instructionGroups": [
    {
      "label": null,
      "steps": [
        { "text": "...", "tip": "..." }
      ]
    }
  ],
  "tips": ["..."],
  "substitutions": [
    { "original": "...", "substitute": "...", "note": "..." }
  ],
  "tags": {
    "cuisine": "...",
    "mealType": "dinner",
    "dietary": ["..."],
    "season": "year-round",
    "cookingMethod": ["..."]
  },
  "nutrition": {
    "calories": 500,
    "protein": "30g",
    "carbs": "40g",
    "fat": "20g",
    "fiber": "5g",
    "sodium": "700mg"
  },
  "sourceNote": "...",
  "imagePrompt": "..."
}

Return JSON only. No markdown. No explanation.`
}

async function callLlm(messages: Array<{ role: string; content: string }>) {
  const response = await fetch(LLM_ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${LLM_API_KEY}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://allio.life',
      'X-Title': 'Allio Public Meal Generator',
    },
    body: JSON.stringify({
      model: LLM_MODEL,
      messages,
      response_format: { type: 'json_object' },
      temperature: 0.8,
    }),
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`OpenRouter error ${response.status}: ${text}`)
  }

  return await response.json()
}

function extractLlmContent(llm: any) {
  const content = llm?.choices?.[0]?.message?.content
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    const text = content
      .map((part) => typeof part?.text === 'string' ? part.text : '')
      .join('')
      .trim()
    if (text) return text
  }
  return ''
}

async function generateRecipe(payload: any) {
  const systemPrompt = buildPrompt(payload)
  const baseMessages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: 'Generate one recipe now.' },
  ]

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const llm = await callLlm(baseMessages)
    const content = extractLlmContent(llm)
    if (!content) throw new Error('LLM returned empty content')

    try {
      const parsed = JSON.parse(content)
      const normalized = normalizeRecipe(parsed)
      const validationError = validateRecipe(normalized)
      if (!validationError) return normalized

      if (attempt === 0) {
        baseMessages.push({
          role: 'user',
          content: `Your previous response was malformed: ${validationError}. Return corrected JSON only, preserving all requested fields.`,
        })
        continue
      }
      throw new Error(validationError)
    } catch (error) {
      if (attempt === 0) {
        baseMessages.push({
          role: 'user',
          content: 'Your previous response was malformed JSON. Return corrected JSON only, with the exact requested schema.',
        })
        continue
      }
      throw error
    }
  }

  throw new Error('Unable to generate recipe')
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  const forwardedFor = req.headers.get('x-forwarded-for') || 'unknown'
  const ip = forwardedFor.split(',')[0].trim() || 'unknown'
  if (!cleanupAndCheckRateLimit(ip)) {
    return new Response(JSON.stringify({ error: 'Too many requests. Please wait a bit and try again.' }), {
      status: 429,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  try {
    if (!LLM_API_KEY) {
      return new Response(JSON.stringify({
        ok: false,
        error: 'Public meal generator is not configured yet. Missing LLM API key.',
      }), {
        status: 503,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const payload = await req.json()
    const recipe = await generateRecipe(payload)

    return new Response(JSON.stringify({ ok: true, recipe }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    console.error('[generate-public-meal] error', error?.message || error)
    return new Response(JSON.stringify({
      ok: false,
      error: 'Sorry, I could not generate a polished recipe right now. Please try again in a moment.',
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
