import { Link } from 'react-router-dom'
import { useDocumentTitle } from '../hooks/useDocumentTitle'

  useDocumentTitle("Terms of Service | Allio")
export function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      {/* Header */}
      <div className="bg-white border-b border-divider">
        <div className="max-w-3xl mx-auto px-4 py-4 flex justify-between items-center">
          <Link to="/" className="font-display text-xl text-text-primary">
            Allio
          </Link>
          <Link to="/" className="text-sm text-text-secondary hover:text-text-primary">
            ← Back to home
          </Link>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="font-display text-3xl text-text-primary mb-8">Terms of Service</h1>
        
        <div className="prose prose-sm max-w-none text-text-secondary space-y-6">
          <p className="text-sm text-text-muted">Last updated: March 2026</p>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">About Allio</h2>
            <p>Allio is a meal planning tool designed to help families organize their weekly meals, generate shopping lists, and coordinate household schedules. It is intended for personal, non-commercial use.</p>
          </section>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">Not Medical Advice</h2>
            <p>Allio provides meal suggestions based on general nutritional guidelines. We are not a healthcare provider, dietitian, or medical professional. The meal plans generated by Allio are not medical advice.</p>
            <p className="mt-2">Users with specific dietary requirements, allergies, health conditions, or medical concerns should:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Review all ingredients in recipes before preparing them</li>
              <li>Consult with a healthcare provider or registered dietitian</li>
              <li>Use their own judgment about what's appropriate for their situation</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">User Responsibility</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Ensuring the accuracy of information you provide</li>
              <li>Checking all ingredients for allergies before cooking</li>
              <li>Safe food handling and cooking practices</li>
              <li>Maintaining the security of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">Service Availability</h2>
            <p>Allio is currently in beta. During this period, the service is provided "as is" without warranties of any kind. We may:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Modify or discontinue features at any time</li>
              <li>Update these terms periodically</li>
              <li>Limit or restrict access to certain features</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">Account Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.</p>
          </section>

          <section>
            <h2 className="font-semibold text-text-primary mb-2">Contact Us</h2>
            <p>For questions about these terms, please contact us at:</p>
            <p className="mt-2">hello@allio.life</p>
          </section>
        </div>
      </div>
    </div>
  )
}