-- Seed data for hybrid recipe system
-- 25 high-quality recipes across categories

INSERT INTO recipes (title, slug, description, cuisine, meal_type, prep_time_minutes, cook_time_minutes, servings, ingredients_json, instructions_json, nutrition_json, dietary_flags_json, allergen_flags_json, equipment_json, tags_json, kid_friendly_score, weeknight_score, leftovers_score, cost_tier, difficulty, source_type) VALUES
(
  'One-Pan Chicken Fajitas',
  'one-pan-chicken-fajitas',
  'Sizzling chicken with bell peppers and onions, ready in under 30 minutes',
  'Mexican',
  'dinner',
  10,
  20,
  4,
  '[
    {"item": "chicken breast", "quantity": "1.5", "unit": "lbs", "notes": "sliced thin"},
    {"item": "bell peppers", "quantity": "3", "unit": "mixed colors", "notes": "sliced"},
    {"item": "onion", "quantity": "1", "unit": "large", "notes": "sliced"},
    {"item": "olive oil", "quantity": "2", "unit": "tbsp"},
    {"item": "chili powder", "quantity": "1", "unit": "tbsp"},
    {"item": "cumin", "quantity": "1", "unit": "tsp"},
    {"item": "garlic", "quantity": "3", "unit": "cloves", "notes": "minced"},
    {"item": "lime", "quantity": "1", "unit": "juiced"},
    {"item": "salt", "quantity": "1", "unit": "tsp"},
    {"item": "flour tortillas", "quantity": "8", "unit": "small"}
  ]'::jsonb,
  '[
    "Heat oil in a large skillet over medium-high heat",
    "Season chicken with chili powder, cumin, salt, and garlic",
    "Cook chicken 5-6 minutes until browned and cooked through",
    "Remove chicken, add peppers and onions, cook 4-5 minutes",
    "Return chicken to pan, add lime juice",
    "Warm tortillas and serve"
  ]'::jsonb,
  '{"calories": 420, "protein": 35, "carbs": 38, "fat": 14}'::jsonb,
  '["high-protein"]'::jsonb,
  '["gluten"]'::jsonb,
  '["skillet", "tongs"]'::jsonb,
  '["quick", "one-pan", "family-friendly", "meal-prep"]'::jsonb,
  8, 9, 7, 'moderate', 'easy', 'seed'
),
(
  'Classic Spaghetti Carbonara',
  'classic-spaghetti-carbonara',
  'Creamy Italian pasta with crispy pancetta and parmesan',
  'Italian',
  'dinner',
  10,
  20,
  4,
  '[
    {"item": "spaghetti", "quantity": "1", "unit": "lb"},
    {"item": "pancetta", "quantity": "8", "unit": "oz", "notes": "cubed"},
    {"item": "eggs", "quantity": "4", "unit": "large"},
    {"item": "parmesan cheese", "quantity": "1", "unit": "cup", "notes": "freshly grated"},
    {"item": "garlic", "quantity": "2", "unit": "cloves", "notes": "minced"},
    {"item": "black pepper", "quantity": "1", "unit": "tsp", "notes": "freshly ground"},
    {"item": "salt", "quantity": "1", "unit": "tbsp", "notes": "for pasta water"}
  ]'::jsonb,
  '[
    "Boil large pot of salted water, cook spaghetti until al dente",
    "While pasta cooks, crisp pancetta in large pan until golden",
    "Add garlic, cook 30 seconds until fragrant",
    "Whisk eggs with parmesan and pepper in bowl",
    "Reserve 1 cup pasta water, drain pasta",
    "Toss hot pasta with pancetta, remove from heat",
    "Quickly mix in egg mixture, tossing constantly",
    "Add pasta water as needed for creamy sauce"
  ]'::jsonb,
  '{"calories": 580, "protein": 24, "carbs": 65, "fat": 26}'::jsonb,
  '["high-protein"]'::jsonb,
  '["gluten", "eggs", "dairy"]'::jsonb,
  '["large-pot", "skillet"]'::jsonb,
  '["classic", "comfort-food", "date-night"]'::jsonb,
  5, 7, 8, 'moderate', 'medium', 'seed'
),
(
  '15-Minute Garlic Shrimp Stir-Fry',
  'garlic-shrimp-stir-fry',
  'Quick and flavorful shrimp with vegetables in garlic sauce',
  'Asian',
  'dinner',
  5,
  10,
  4,
  '[
    {"item": "shrimp", "quantity": "1.5", "unit": "lbs", "notes": "peeled, deveined"},
    {"item": "broccoli florets", "quantity": "2", "unit": "cups"},
    {"item": "bell pepper", "quantity": "1", "unit": "sliced"},
    {"item": "garlic", "quantity": "6", "unit": "cloves", "notes": "minced"},
    {"item": "soy sauce", "quantity": "3", "unit": "tbsp"},
    {"item": "sesame oil", "quantity": "1", "unit": "tbsp"},
    {"item": "vegetable oil", "quantity": "2", "unit": "tbsp"},
    {"item": "rice", "quantity": "2", "unit": "cups", "notes": "cooked"}
  ]'::jsonb,
  '[
    "Heat vegetable oil in wok over high heat",
    "Add shrimp, cook 2 minutes until pink, remove",
    "Add broccoli and pepper, stir-fry 3 minutes",
    "Add garlic, cook 30 seconds",
    "Return shrimp, add soy sauce and sesame oil",
    "Toss everything together, serve over rice"
  ]'::jsonb,
  '{"calories": 380, "protein": 32, "carbs": 42, "fat": 12}'::jsonb,
  '["high-protein", "gluten-free"]'::jsonb,
  '["shellfish", "soy"]'::jsonb,
  '["wok", "large-skillet"]'::jsonb,
  '["quick", "low-carb", "healthy"]'::jsonb,
  6, 10, 5, 'moderate', 'easy', 'seed'
),
(
  'Sheet Pan Salmon with Roasted Vegetables',
  'sheet-pan-salmon-vegetables',
  'Hearty salmon fillet with colorful roasted seasonal vegetables',
  'American',
  'dinner',
  10,
  25,
  4,
  '[
    {"item": "salmon fillets", "quantity": "4", "unit": "6-oz", "notes": "skin-on"},
    {"item": "asparagus", "quantity": "1", "unit": "bunch", "notes": "trimmed"},
    {"item": "cherry tomatoes", "quantity": "2", "unit": "cups"},
    {"item": "zucchini", "quantity": "2", "unit": "sliced"},
    {"item": "olive oil", "quantity": "3", "unit": "tbsp"},
    {"item": "lemon", "quantity": "1", "unit": "sliced"},
    {"item": "dill", "quantity": "2", "unit": "tbsp", "notes": "fresh, chopped"},
    {"item": "garlic", "quantity": "3", "unit": "cloves", "notes": "minced"},
    {"item": "salt and pepper", "quantity": "1", "unit": "to taste"}
  ]'::jsonb,
  '[
    "Preheat oven to 400°F",
    "Toss vegetables with 2 tbsp oil, salt, pepper on sheet pan",
    "Roast vegetables 10 minutes",
    "Season salmon with garlic, dill, remaining oil, salt, pepper",
    "Add salmon and lemon slices to pan",
    "Roast 12-15 minutes until salmon flakes easily"
  ]'::jsonb,
  '{"calories": 450, "protein": 42, "carbs": 12, "fat": 26}'::jsonb,
  '["high-protein", "gluten-free", "dairy-free", "low-carb"]'::jsonb,
  '["fish"]'::jsonb,
  '["sheet-pan"]'::jsonb,
  '["healthy", "easy-cleanup", "omega-3"]'::jsonb,
  7, 9, 7, 'moderate', 'easy', 'seed'
),
(
  'Slow Cooker Pulled Pork',
  'slow-cooker-pulled-pork',
  'Tender, smoky pulled pork perfect for sandwiches or tacos',
  'American',
  'dinner',
  15,
  480,
  10,
  '[
    {"item": "pork shoulder", "quantity": "4", "unit": "lbs", "notes": "bone-in"},
    {"item": "brown sugar", "quantity": "1/2", "unit": "cup"},
    {"item": "paprika", "quantity": "2", "unit": "tbsp"},
    {"item": "garlic powder", "quantity": "1", "unit": "tbsp"},
    {"item": "onion powder", "quantity": "1", "unit": "tbsp"},
    {"item": "cayenne pepper", "quantity": "1", "unit": "tsp"},
    {"item": "salt", "quantity": "1", "unit": "tbsp"},
    {"item": "apple cider vinegar", "quantity": "1/2", "unit": "cup"},
    {"item": "bbq sauce", "quantity": "1", "unit": "cup"}
  ]'::jsonb,
  '[
    "Mix brown sugar and spices to make dry rub",
    "Pat pork dry, coat generously with rub",
    "Place pork in slow cooker, add vinegar",
    "Cook on low 8 hours until fork-tender",
    "Shred pork with two forks, discard bone",
    "Mix in BBQ sauce or serve on side"
  ]'::jsonb,
  '{"calories": 380, "protein": 36, "carbs": 18, "fat": 22}'::jsonb,
  '["high-protein", "dairy-free"]'::jsonb,
  '[]'::jsonb,
  '["slow-cooker"]'::jsonb,
  '["meal-prep", "crowd-pleaser", "freezer-friendly"]'::jsonb,
  9, 6, 10, 'budget', 'easy', 'seed'
),
(
  'Vegetable Thai Green Curry',
  'vegetable-thai-green-curry',
  'Aromatic coconut curry loaded with vegetables',
  'Thai',
  'dinner',
  15,
  25,
  4,
  '[
    {"item": "tofu", "quantity": "14", "unit": "oz", "notes": "extra-firm, cubed"},
    {"item": "coconut milk", "quantity": "1", "unit": "can", "notes": "full-fat"},
    {"item": "green curry paste", "quantity": "3", "unit": "tbsp"},
    {"item": "vegetable broth", "quantity": "1", "unit": "cup"},
    {"item": "bamboo shoots", "quantity": "1", "unit": "cup"},
    {"item": "bell pepper", "quantity": "1", "unit": "sliced"},
    {"item": "zucchini", "quantity": "1", "unit": "sliced"},
    {"item": "baby corn", "quantity": "1", "unit": "cup"},
    {"item": "basil", "quantity": "1/2", "unit": "cup", "notes": "fresh Thai basil"},
    {"item": "jasmine rice", "quantity": "2", "unit": "cups", "notes": "cooked"}
  ]'::jsonb,
  '[
    "Fry tofu cubes until golden, set aside",
    "Heat thick coconut cream, add curry paste, fry 2 min",
    "Add remaining coconut milk and broth",
    "Add vegetables, simmer 10 minutes",
    "Return tofu, cook 5 more minutes",
    "Stir in basil, serve over jasmine rice"
  ]'::jsonb,
  '{"calories": 420, "protein": 18, "carbs": 45, "fat": 22}'::jsonb,
  '["vegetarian", "vegan", "gluten-free"]'::jsonb,
  '["soy"]'::jsonb,
  '["wok", "skillet"]'::jsonb,
  '["quick", "flavorful", "healthy"]'::jsonb,
  7, 8, 6, 'moderate', 'medium', 'seed'
),
(
  'Classic Beef Tacos',
  'classic-beef-tacos',
  'Seasoned ground beef tacos with fresh toppings',
  'Mexican',
  'dinner',
  10,
  15,
  6,
  '[
    {"item": "ground beef", "quantity": "1.5", "unit": "lbs"},
    {"item": "taco seasoning", "quantity": "2", "unit": "tbsp", "notes": "or homemade"},
    {"item": "taco shells", "quantity": "12", "unit": "shells"},
    {"item": "lettuce", "quantity": "2", "unit": "cups", "notes": "shredded"},
    {"item": "tomatoes", "quantity": "2", "unit": "diced"},
    {"item": "cheddar cheese", "quantity": "1", "unit": "cup", "notes": "shredded"},
    {"item": "sour cream", "quantity": "1/2", "unit": "cup"},
    {"item": "salsa", "quantity": "1/2", "unit": "cup"}
  ]'::jsonb,
  '[
    "Brown ground beef in skillet over medium-high heat",
    "Drain excess fat, add taco seasoning and 1/4 cup water",
    "Simmer 5 minutes until thickened",
    "Warm taco shells according to package",
    "Fill shells with beef, top with lettuce, tomatoes, cheese",
    "Serve with sour cream and salsa"
  ]'::jsonb,
  '{"calories": 380, "protein": 22, "carbs": 28, "fat": 20}'::jsonb,
  '["high-protein"]'::jsonb,
  '["gluten", "dairy"]'::jsonb,
  '["skillet"]'::jsonb,
  '["quick", "family-friendly", "customizable"]'::jsonb,
  9, 10, 6, 'budget', 'easy', 'seed'
),
(
  'Creamy Tomato Soup with Grilled Cheese',
  'creamy-tomato-soup-grilled-cheese',
  'Comforting homemade tomato soup with gooey grilled cheese',
  'American',
  'dinner',
  10,
  30,
  4,
  '[
    {"item": "canned crushed tomatoes", "quantity": "2", "unit": "cans (28 oz)"},
    {"item": "onion", "quantity": "1", "unit": "diced"},
    {"item": "garlic", "quantity": "4", "unit": "cloves", "notes": "minced"},
    {"item": "vegetable broth", "quantity": "2", "unit": "cups"},
    {"item": "heavy cream", "quantity": "1/2", "unit": "cup"},
    {"item": "butter", "quantity": "3", "unit": "tbsp"},
    {"item": "basil", "quantity": "1/4", "unit": "cup", "notes": "fresh, chopped"},
    {"item": "bread", "quantity": "8", "unit": "slices"},
    {"item": "cheddar cheese", "quantity": "4", "unit": "slices"}
  ]'::jsonb,
  '[
    "Sauté onion in butter until soft, add garlic",
    "Add tomatoes and broth, simmer 20 minutes",
    "Blend until smooth, stir in cream and basil",
    "For grilled cheese: butter bread, add cheese, grill until golden",
    "Cut sandwiches in half, serve with soup"
  ]'::jsonb,
  '{"calories": 480, "protein": 14, "carbs": 42, "fat": 28}'::jsonb,
  '["vegetarian"]'::jsonb,
  '["gluten", "dairy"]'::jsonb,
  '["pot", "blender", "skillet"]'::jsonb,
  '["comfort-food", "kid-friendly", "classic"]'::jsonb,
  9, 8, 8, 'budget', 'easy', 'seed'
),
(
  'Mediterranean Quinoa Bowl',
  'mediterranean-quinoa-bowl',
  'Protein-rich quinoa with fresh vegetables and feta',
  'Mediterranean',
  'lunch',
  15,
  20,
  4,
  '[
    {"item": "quinoa", "quantity": "1.5", "unit": "cups", "notes": "uncooked"},
    {"item": "cucumber", "quantity": "1", "unit": "diced"},
    {"item": "cherry tomatoes", "quantity": "1", "unit": "cup", "notes": "halved"},
    {"item": "red onion", "quantity": "1/2", "unit": "cup", "notes": "diced"},
    {"item": "kalamata olives", "quantity": "1/2", "unit": "cup"},
    {"item": "feta cheese", "quantity": "1/2", "unit": "cup", "notes": "crumbled"},
    {"item": "chickpeas", "quantity": "1", "unit": "can", "notes": "drained"},
    {"item": "olive oil", "quantity": "3", "unit": "tbsp"},
    {"item": "lemon", "quantity": "1", "unit": "juiced"},
    {"item": "oregano", "quantity": "1", "unit": "tsp", "notes": "dried"}
  ]'::jsonb,
  '[
    "Cook quinoa according to package, let cool",
    "Combine cucumber, tomatoes, onion, olives, chickpeas",
    "Whisk olive oil, lemon juice, oregano for dressing",
    "Toss everything with quinoa",
    "Top with feta cheese"
  ]'::jsonb,
  '{"calories": 420, "protein": 15, "carbs": 48, "fat": 18}'::jsonb,
  '["vegetarian", "high-protein", "gluten-free"]'::jsonb,
  '["dairy"]'::jsonb,
  '["pot", "large-bowl"]'::jsonb,
  '["healthy", "meal-prep", "no-cook"]'::jsonb,
  8, 10, 8, 'budget', 'easy', 'seed'
),
(
  'Chicken Caesar Salad',
  'chicken-caesar-salad',
  'Classic Caesar with grilled chicken breast',
  'American',
  'lunch',
  15,
  15,
  2,
  '[
    {"item": "chicken breast", "quantity": "2", "unit": "6-oz"},
    {"item": "romaine lettuce", "quantity": "1", "unit": "head", "notes": "chopped"},
    {"item": "parmesan cheese", "quantity": "1/2", "unit": "cup", "notes": "shaved"},
    {"item": "caesar dressing", "quantity": "1/2", "unit": "cup"},
    {"item": "croutons", "quantity": "1", "unit": "cup"},
    {"item": "lemon", "quantity": "1", "unit": "wedged"},
    {"item": "black pepper", "quantity": "1", "unit": "to taste"}
  ]'::jsonb,
  '[
    "Season chicken with salt and pepper",
    "Grill or pan-sear chicken 6 minutes per side",
    "Let rest 5 minutes, slice thin",
    "Toss lettuce with Caesar dressing",
    "Top with chicken, parmesan, croutons",
    "Serve with lemon wedge"
  ]'::jsonb,
  '{"calories": 380, "protein": 35, "carbs": 15, "fat": 22}'::jsonb,
  '["high-protein", "gluten-free"]'::jsonb,
  '["dairy", "eggs", "fish", "gluten"]'::jsonb,
  '["grill-pan", "large-bowl"]'::jsonb,
  '["quick", "classic", "protein-packed"]'::jsonb,
  7, 10, 5, 'moderate', 'easy', 'seed'
),
(
  'Overnight Oats Three Ways',
  'overnight-oats-three-ways',
  'Easy meal-prep breakfast with customizable flavors',
  'American',
  'breakfast',
  5,
  0,
  3,
  '[
    {"item": "rolled oats", "quantity": "1.5", "unit": "cups"},
    {"item": "milk", "quantity": "1.5", "unit": "cups", "notes": "any kind"},
    {"item": "greek yogurt", "quantity": "3/4", "unit": "cup"},
    {"item": "chia seeds", "quantity": "3", "unit": "tbsp"},
    {"item": "maple syrup", "quantity": "3", "unit": "tbsp"},
    {"item": "vanilla extract", "quantity": "1", "unit": "tsp"},
    {"item": "blueberries", "quantity": "1/2", "unit": "cup", "notes": "for berry version"},
    {"item": "peanut butter", "quantity": "2", "unit": "tbsp", "notes": "for PB version"},
    {"item": "banana", "quantity": "1", "unit": "sliced", "notes": "for banana version"}
  ]'::jsonb,
  '[
    "Combine oats, milk, yogurt, chia seeds, maple syrup, vanilla in jars",
    "Divide into three portions",
    "Add blueberries to one, peanut butter to second, banana to third",
    "Stir well, cover, refrigerate overnight",
    "In morning, add more milk if needed, enjoy cold"
  ]'::jsonb,
  '{"calories": 320, "protein": 12, "carbs": 52, "fat": 8}'::jsonb,
  '["vegetarian", "high-protein", "dairy-free-option"]'::jsonb,
  '["dairy", "gluten"]'::jsonb,
  '["jars", "refrigerator"]'::jsonb,
  '["meal-prep", "no-cook", "healthy", "customizable"]'::jsonb,
  10, 10, 9, 'budget', 'easy', 'seed'
),
(
  'Fluffy Pancakes',
  'fluffy-pancakes',
  'Light and fluffy buttermilk pancakes for weekend brunch',
  'American',
  'breakfast',
  10,
  15,
  4,
  '[
    {"item": "all-purpose flour", "quantity": "1.5", "unit": "cups"},
    {"item": "buttermilk", "quantity": "1.5", "unit": "cups"},
    {"item": "eggs", "quantity": "2", "unit": "large"},
    {"item": "butter", "quantity": "3", "unit": "tbsp", "notes": "melted"},
    {"item": "sugar", "quantity": "2", "unit": "tbsp"},
    {"item": "baking powder", "quantity": "1.5", "unit": "tsp"},
    {"item": "baking soda", "quantity": "1/2", "unit": "tsp"},
    {"item": "salt", "quantity": "1/2", "unit": "tsp"},
    {"item": "maple syrup", "quantity": "1/2", "unit": "cup", "notes": "for serving"}
  ]'::jsonb,
  '[
    "Mix flour, sugar, baking powder, baking soda, salt in bowl",
    "Whisk buttermilk, eggs, melted butter in another bowl",
    "Pour wet into dry, stir until just combined (lumps OK)",
    "Heat griddle over medium heat, lightly grease",
    "Pour 1/4 cup batter per pancake",
    "Flip when bubbles form, cook until golden",
    "Serve with butter and maple syrup"
  ]'::jsonb,
  '{"calories": 380, "protein": 10, "carbs": 58, "fat": 12}'::jsonb,
  '["vegetarian"]'::jsonb,
  '["gluten", "dairy", "eggs"]'::jsonb,
  '["griddle", "mixing-bowls"]'::jsonb,
  '["weekend", "family-friendly", "comfort-food"]'::jsonb,
  10, 7, 7, 'budget', 'easy', 'seed'
),
(
  'Avocado Toast with Eggs',
  'avocado-toast-eggs',
  'Trendy avocado toast with perfectly poached or scrambled eggs',
  'American',
  'breakfast',
  5,
  10,
  2,
  '[
    {"item": "sourdough bread", "quantity": "2", "unit": "slices"},
    {"item": "avocado", "quantity": "1", "unit": "ripe"},
    {"item": "eggs", "quantity": "2", "unit": "large"},
    {"item": "cherry tomatoes", "quantity": "1/2", "unit": "cup", "notes": "halved"},
    {"item": "red pepper flakes", "quantity": "1/4", "unit": "tsp"},
    {"item": "salt and pepper", "quantity": "1", "unit": "to taste"},
    {"item": "lime", "quantity": "1", "unit": "juiced"},
    {"item": "everything bagel seasoning", "quantity": "1", "unit": "tsp", "notes": "optional"}
  ]'::jsonb,
  '[
    "Toast bread until golden and crispy",
    "Mash avocado with lime juice, salt, pepper",
    "Poach or scramble eggs to preference",
    "Spread avocado on toast, top with eggs",
    "Add tomatoes, sprinkle with seasonings",
    "Serve immediately"
  ]'::jsonb,
  '{"calories": 340, "protein": 14, "carbs": 28, "fat": 20}'::jsonb,
  '["vegetarian", "high-protein"]'::jsonb,
  '["gluten", "eggs"]'::jsonb,
  '["toaster", "skillet"]'::jsonb,
  '["quick", "healthy", "trendy"]'::jsonb,
  7, 10, 4, 'budget', 'easy', 'seed'
),
(
  'Black Bean Tacos',
  'black-bean-tacos',
  'Hearty vegetarian tacos with seasoned black beans',
  'Mexican',
  'dinner',
  10,
  15,
  4,
  '[
    {"item": "black beans", "quantity": "2", "unit": "cans", "notes": "drained"},
    {"item": "corn tortillas", "quantity": "12", "unit": "small"},
    {"item": "onion", "quantity": "1", "unit": "diced"},
    {"item": "garlic", "quantity": "2", "unit": "cloves", "notes": "minced"},
    {"item": "cumin", "quantity": "1", "unit": "tbsp"},
    {"item": "chili powder", "quantity": "1", "unit": "tbsp"},
    {"item": "lime", "quantity": "2", "unit": "juiced"},
    {"item": "cilantro", "quantity": "1/2", "unit": "cup", "notes": "fresh, chopped"},
    {"item": "avocado", "quantity": "1", "unit": "sliced"},
    {"item": "salsa verde", "quantity": "1/2", "unit": "cup"}
  ]'::jsonb,
  '[
    "Sauté onion until soft, add garlic",
    "Add beans, cumin, chili powder, 1/2 cup water",
    "Mash beans slightly, simmer 10 minutes",
    "Add lime juice, taste and adjust seasoning",
    "Warm tortillas",
    "Fill tortillas with beans, top with cilantro, avocado, salsa"
  ]'::jsonb,
  '{"calories": 320, "protein": 14, "carbs": 52, "fat": 10}'::jsonb,
  '["vegetarian", "vegan", "high-fiber"]'::jsonb,
  '[]'::jsonb,
  '["skillet"]'::jsonb,
  '["quick", "meatless-monday", "budget-friendly"]'::jsonb,
  8, 10, 7, 'budget', 'easy', 'seed'
),
(
  'Lemon Herb Roasted Chicken',
  'lemon-herb-roasted-chicken',
  'Classic whole roasted chicken with lemon and herbs',
  'American',
  'dinner',
  20,
  75,
  6,
  '[
    {"item": "whole chicken", "quantity": "1", "unit": "4-5 lbs"},
    {"item": "lemons", "quantity": "2", "unit": "one sliced, one juiced"},
    {"item": "garlic", "quantity": "1", "unit": "head", "notes": "halved"},
    {"item": "rosemary", "quantity": "4", "unit": "sprigs"},
    {"item": "thyme", "quantity": "6", "unit": "sprigs"},
    {"item": "butter", "quantity": "4", "unit": "tbsp", "notes": "softened"},
    {"item": "olive oil", "quantity": "2", "unit": "tbsp"},
    {"item": "salt", "quantity": "1", "unit": "tbsp"},
    {"item": "pepper", "quantity": "1", "unit": "tsp"}
  ]'::jsonb,
  '[
    "Preheat oven to 425°F",
    "Pat chicken dry, rub with butter under and over skin",
    "Season generously inside and out with salt and pepper",
    "Stuff cavity with lemon halves, garlic, herbs",
    "Place sliced lemon and herbs under and around chicken",
    "Roast 1 hour 15 minutes until juices run clear",
    "Rest 15 minutes before carving"
  ]'::jsonb,
  '{"calories": 420, "protein": 42, "carbs": 2, "fat": 28}'::jsonb,
  '["high-protein", "gluten-free", "dairy-free"]'::jsonb,
  '[]'::jsonb,
  '["roasting-pan"]'::jsonb,
  '["Sunday-dinner", "impressive", "crowd-pleaser"]'::jsonb,
  8, 5, 9, 'moderate', 'medium', 'seed'
),
(
  'Caprese Pasta Salad',
  'caprese-pasta-salad',
  'Fresh pasta salad with tomatoes, mozzarella, and basil',
  'Italian',
  'lunch',
  15,
  10,
  6,
  '[
    {"item": "penne pasta", "quantity": "1", "unit": "lb"},
    {"item": "cherry tomatoes", "quantity": "2", "unit": "cups", "notes": "halved"},
    {"item": "mozzarella", "quantity": "8", "unit": "oz", "notes": "cubed"},
    {"item": "fresh mozzarella", "quantity": "4", "unit": "oz", "notes": "bocconcini"},
    {"item": "basil", "quantity": "1/2", "unit": "cup", "notes": "fresh leaves"},
    {"item": "olive oil", "quantity": "1/4", "unit": "cup"},
    {"item": "balsamic glaze", "quantity": "2", "unit": "tbsp"},
    {"item": "garlic", "quantity": "2", "unit": "cloves", "notes": "minced"},
    {"item": "salt and pepper", "quantity": "1", "unit": "to taste"}
  ]'::jsonb,
  '[
    "Cook pasta until al dente, drain and cool",
    "Whisk olive oil, garlic, salt, pepper for dressing",
    "Toss pasta with tomatoes, mozzarella, basil",
    "Add dressing, toss to combine",
    "Drizzle with balsamic glaze",
    "Serve at room temperature or chilled"
  ]'::jsonb,
  '{"calories": 380, "protein": 14, "carbs": 45, "fat": 16}'::jsonb,
  '["vegetarian"]'::jsonb,
  '["gluten", "dairy"]'::jsonb,
  '["pot", "large-bowl"]'::jsonb,
  '["no-cook", "meal-prep", "potluck"]'::jsonb,
  9, 10, 8, 'budget', 'easy', 'seed'
),
(
  'Honey Garlic Salmon',
  'honey-garlic-salmon',
  'Sweet and savory salmon fillets in honey garlic sauce',
  'Asian',
  'dinner',
  5,
  15,
  4,
  '[
    {"item": "salmon fillets", "quantity": "4", "unit": "6-oz"},
    {"item": "honey", "quantity": "1/4", "unit": "cup"},
    {"item": "soy sauce", "quantity": "3", "unit": "tbsp"},
    {"item": "garlic", "quantity": "4", "unit": "cloves", "notes": "minced"},
    {"item": "lemon", "quantity": "1", "unit": "juiced"},
    {"item": "olive oil", "quantity": "1", "unit": "tbsp"},
    {"item": "sesame seeds", "quantity": "1", "unit": "tbsp"},
    {"item": "green onions", "quantity": "2", "unit": "sliced"}
  ]'::jsonb,
  '[
    "Mix honey, soy sauce, garlic, lemon juice",
    "Heat oil in skillet over medium-high",
    "Sear salmon skin-side up 4 minutes",
    "Flip, pour sauce over salmon",
    "Cook 4-5 minutes until salmon done",
    "Garnish with sesame seeds and green onions"
  ]'::jsonb,
  '{"calories": 440, "protein": 40, "carbs": 22, "fat": 22}'::jsonb,
  '["high-protein", "gluten-free"]'::jsonb,
  '["fish", "soy"]'::jsonb,
  '["skillet"]'::jsonb,
  '["quick", "restaurant-quality", "weeknight"]'::jsonb,
  8, 10, 6, 'moderate', 'easy', 'seed'
),
(
  'Turkey Meatball Subs',
  'turkey-meatball-subs',
  'Homemade turkey meatballs in marinara on crusty rolls',
  'American',
  'dinner',
  20,
  25,
  4,
  '[
    {"item": "ground turkey", "quantity": "1.5", "unit": "lbs"},
    {"item": "breadcrumbs", "quantity": "1/2", "unit": "cup"},
    {"item": "parmesan cheese", "quantity": "1/4", "unit": "cup", "notes": "grated"},
    {"item": "egg", "quantity": "1", "unit": "large"},
    {"item": "Italian seasoning", "quantity": "1", "unit": "tsp"},
    {"item": "garlic", "quantity": "3", "unit": "cloves", "notes": "minced"},
    {"item": "marinara sauce", "quantity": "2", "unit": "cups"},
    {"item": "sub rolls", "quantity": "4", "unit": "large"},
    {"item": "mozzarella", "quantity": "1", "unit": "cup", "notes": "shredded"}
  ]'::jsonb,
  '[
    "Mix turkey, breadcrumbs, parmesan, egg, seasoning, garlic",
    "Form into 12 meatballs, bake at 400°F for 15 min",
    "Simmer meatballs in marinara 10 minutes",
    "Split rolls, fill with meatballs and sauce",
    "Top with mozzarella, broil until melted",
    "Serve immediately"
  ]'::jsonb,
  '{"calories": 520, "protein": 38, "carbs": 48, "fat": 20}'::jsonb,
  '["high-protein"]'::jsonb,
  '["gluten", "dairy", "eggs"]'::jsonb,
  '["baking-sheet", "skillet"]'::jsonb,
  '["family-friendly", "comfort-food"]'::jsonb,
  9, 8, 7, 'budget', 'medium', 'seed'
),
(
  'Greek Salad',
  'greek-salad',
  'Fresh Mediterranean salad with olives and feta',
  'Greek',
  'lunch',
  10,
  0,
  4,
  '[
    {"item": "cucumber", "quantity": "1", "unit": "large", "notes": "quartered moons"},
    {"item": "tomatoes", "quantity": "2", "unit": "large", "notes": "wedges"},
    {"item": "red onion", "quantity": "1/2", "unit": "thinly sliced"},
    {"item": "kalamata olives", "quantity": "1/2", "unit": "cup"},
    {"item": "feta cheese", "quantity": "1/2", "unit": "cup", "notes": "cubed"},
    {"item": "olive oil", "quantity": "4", "unit": "tbsp"},
    {"item": "red wine vinegar", "quantity": "2", "unit": "tbsp"},
    {"item": "oregano", "quantity": "1", "unit": "tsp", "notes": "dried"},
    {"item": "salt and pepper", "quantity": "1", "unit": "to taste"}
  ]'::jsonb,
  '[
    "Combine cucumber, tomatoes, onion, olives in bowl",
    "Whisk olive oil, vinegar, oregano, salt, pepper",
    "Pour dressing over salad, toss gently",
    "Top with feta cheese",
    "Serve immediately or chill"
  ]'::jsonb,
  '{"calories": 280, "protein": 8, "carbs": 14, "fat": 22}'::jsonb,
  '["vegetarian", "gluten-free", "low-carb"]'::jsonb,
  '["dairy"]'::jsonb,
  '["large-bowl"]'::jsonb,
  '["quick", "healthy", "no-cook", "mediterranean"]'::jsonb,
  8, 10, 9, 'budget', 'easy', 'seed'
),
(
  'Beef and Broccoli',
  'beef-and-broccoli',
  'Classic Chinese-American takeout favorite',
  'Chinese',
  'dinner',
  15,
  15,
  4,
  '[
    {"item": "flank steak", "quantity": "1.5", "unit": "lbs", "notes": "sliced thin"},
    {"item": "broccoli florets", "quantity": "3", "unit": "cups"},
    {"item": "soy sauce", "quantity": "1/4", "unit": "cup"},
    {"item": "oyster sauce", "quantity": "2", "unit": "tbsp"},
    {"item": "sesame oil", "quantity": "1", "unit": "tbsp"},
    {"item": "garlic", "quantity": "3", "unit": "cloves", "notes": "minced"},
    {"item": "ginger", "quantity": "1", "unit": "tbsp", "notes": "minced"},
    {"item": "cornstarch", "quantity": "1", "unit": "tbsp"},
    {"item": "vegetable oil", "quantity": "2", "unit": "tbsp"},
    {"item": "rice", "quantity": "2", "unit": "cups", "notes": "cooked"}
  ]'::jsonb,
  '[
    "Mix soy sauce, oyster sauce, sesame oil, cornstarch for sauce",
    "Heat oil in wok over high heat",
    "Stir-fry beef 2 minutes until browned, remove",
    "Add broccoli, stir-fry 3 minutes",
    "Add garlic and ginger, cook 30 seconds",
    "Return beef, add sauce, toss until thickened",
    "Serve over rice"
  ]'::jsonb,
  '{"calories": 460, "protein": 38, "carbs": 38, "fat": 20}'::jsonb,
  '["high-protein"]'::jsonb,
  '["soy"]'::jsonb,
  '["wok", "skillet"]'::jsonb,
  '["quick", "takeout-fakeout", "family-favorite"]'::jsonb,
  7, 10, 5, 'moderate', 'medium', 'seed'
),
(
  'Spinach and Feta Stuffed Chicken',
  'spinach-feta-stuffed-chicken',
  'Juicy chicken breasts stuffed with creamy spinach and feta',
  'Mediterranean',
  'dinner',
  15,
  30,
  4,
  '[
    {"item": "chicken breasts", "quantity": "4", "unit": "6-oz", "notes": "butterflied"},
    {"item": "frozen spinach", "quantity": "10", "unit": "oz", "notes": "thawed, drained"},
    {"item": "feta cheese", "quantity": "1/2", "unit": "cup", "notes": "crumbled"},
    {"item": "cream cheese", "quantity": "4", "unit": "oz", "notes": "softened"},
    {"item": "garlic", "quantity": "2", "unit": "cloves", "notes": "minced"},
    {"item": "sun-dried tomatoes", "quantity": "1/4", "unit": "cup", "notes": "chopped"},
    {"item": "olive oil", "quantity": "2", "unit": "tbsp"},
    {"item": "Italian seasoning", "quantity": "1", "unit": "tsp"},
    {"item": "salt and pepper", "quantity": "1", "unit": "to taste"}
  ]'::jsonb,
  '[
    "Mix spinach, feta, cream cheese, garlic, tomatoes",
    "Season chicken inside and out",
    "Divide filling among chicken breasts, fold closed",
    "Secure with toothpicks if needed",
    "Sear in oil 4 minutes per side",
    "Finish in 375°F oven 15-20 minutes until done",
    "Rest 5 minutes before serving"
  ]'::jsonb,
  '{"calories": 380, "protein": 42, "carbs": 6, "fat": 22}'::jsonb,
  '["high-protein", "low-carb", "gluten-free"]'::jsonb,
  '["dairy"]'::jsonb,
  '["skillet", "oven-safe"]'::jsonb,
  '["impressive", "low-carb", "protein-packed"]'::jsonb,
  6, 7, 7, 'moderate', 'medium', 'seed'
),
(
  'Banana Oat Smoothie Bowl',
  'banana-oat-smoothie-bowl',
  'Thick smoothie bowl topped with fresh fruit and granola',
  'American',
  'breakfast',
  5,
  0,
  1,
  '[
    {"item": "frozen banana", "quantity": "1", "unit": "large"},
    {"item": "rolled oats", "quantity": "1/4", "unit": "cup"},
    {"item": "milk", "quantity": "1/2", "unit": "cup", "notes": "any kind"},
    {"item": "almond butter", "quantity": "1", "unit": "tbsp"},
    {"item": "honey", "quantity": "1", "unit": "tbsp"},
    {"item": "granola", "quantity": "1/4", "unit": "cup"},
    {"item": "fresh berries", "quantity": "1/2", "unit": "cup"},
    {"item": "chia seeds", "quantity": "1", "unit": "tsp"},
    {"item": "coconut flakes", "quantity": "1", "unit": "tbsp"}
  ]'::jsonb,
  '[
    "Blend banana, oats, milk, almond butter, honey until thick",
    "Pour into bowl (should be thick, not pourable)",
    "Top with granola, berries, chia seeds, coconut",
    "Serve immediately"
  ]'::jsonb,
  '{"calories": 380, "protein": 10, "carbs": 62, "fat": 12}'::jsonb,
  '["vegetarian", "high-fiber"]'::jsonb,
  '["gluten", "nuts"]'::jsonb,
  '["blender"]'::jsonb,
  '["quick", "healthy", "trendy", "no-cook"]'::jsonb,
  9, 10, 6, 'budget', 'easy', 'seed'
),
(
  'Baked Ziti',
  'baked-ziti',
  'Cheesy baked pasta casserole comfort food',
  'Italian',
  'dinner',
  20,
  35,
  8,
  '[
    {"item": "ziti pasta", "quantity": "1", "unit": "lb"},
    {"item": "ricotta cheese", "quantity": "15", "unit": "oz"},
    {"item": "mozzarella", "quantity": "3", "unit": "cups", "notes": "shredded"},
    {"item": "parmesan cheese", "quantity": "1/2", "unit": "cup", "notes": "grated"},
    {"item": "marinara sauce", "quantity": "3", "unit": "cups"},
    {"item": "egg", "quantity": "1", "unit": "large"},
    {"item": "Italian herbs", "quantity": "1", "unit": "tbsp"},
    {"item": "garlic", "quantity": "3", "unit": "cloves", "notes": "minced"},
    {"item": "salt", "quantity": "1", "unit": "tsp"}
  ]'::jsonb,
  '[
    "Preheat oven to 375°F",
    "Cook pasta until just shy of al dente",
    "Mix ricotta, half the mozzarella, egg, herbs, garlic",
    "Toss pasta with marinara, then with cheese mixture",
    "Pour into 9x13 baking dish",
    "Top with remaining mozzarella and parmesan",
    "Cover, bake 25 minutes, uncover 10 minutes until bubbly"
  ]'::jsonb,
  '{"calories": 480, "protein": 22, "carbs": 52, "fat": 20}'::jsonb,
  '["vegetarian"]'::jsonb,
  '["gluten", "dairy", "eggs"]'::jsonb,
  '["pot", "9x13-pan"]'::jsonb,
  '["comfort-food", "crowd-pleaser", "freezer-friendly"]'::jsonb,
  9, 6, 9, 'budget', 'easy', 'seed'
),
(
  'Teriyaki Chicken Rice Bowls',
  'teriyaki-chicken-rice-bowls',
  'Sweet and sticky teriyaki chicken over steamed rice',
  'Japanese',
  'dinner',
  10,
  20,
  4,
  '[
    {"item": "chicken thighs", "quantity": "1.5", "unit": "lbs", "notes": "boneless"},
    {"item": "rice", "quantity": "2", "unit": "cups", "notes": "cooked"},
    {"item": "soy sauce", "quantity": "1/2", "unit": "cup"},
    {"item": "honey", "quantity": "1/4", "unit": "cup"},
    {"item": "mirin", "quantity": "2", "unit": "tbsp"},
    {"item": "ginger", "quantity": "1", "unit": "tbsp", "notes": "minced"},
    {"item": "garlic", "quantity": "2", "unit": "cloves", "notes": "minced"},
    {"item": "sesame seeds", "quantity": "1", "unit": "tbsp"},
    {"item": "green onions", "quantity": "3", "unit": "sliced"},
    {"item": "broccoli", "quantity": "2", "unit": "cups", "notes": "steamed"}
  ]'::jsonb,
  '[
    "Mix soy sauce, honey, mirin, ginger, garlic for teriyaki",
    "Cook chicken in skillet until browned",
    "Add sauce, simmer 10 minutes until thickened",
    "Slice chicken, return to sauce",
    "Serve over rice with steamed broccoli",
    "Garnish with sesame seeds and green onions"
  ]'::jsonb,
  '{"calories": 520, "protein": 36, "carbs": 58, "fat": 14}'::jsonb,
  '["high-protein"]'::jsonb,
  '["soy", "gluten"]'::jsonb,
  '["skillet"]'::jsonb,
  '["family-friendly", "meal-prep", "takeout-fakeout"]'::jsonb,
  9, 9, 8, 'budget', 'easy', 'seed'
),
(
  'Shrimp Scampi',
  'shrimp-scampi',
  'Garlicky shrimp in white wine butter sauce over pasta',
  'Italian',
  'dinner',
  10,
  15,
  4,
  '[
    {"item": "shrimp", "quantity": "1.5", "unit": "lbs", "notes": "peeled, deveined"},
    {"item": "linguine", "quantity": "1", "unit": "lb"},
    {"item": "butter", "quantity": "4", "unit": "tbsp"},
    {"item": "garlic", "quantity": "6", "unit": "cloves", "notes": "minced"},
    {"item": "white wine", "quantity": "1/2", "unit": "cup"},
    {"item": "lemon", "quantity": "1", "unit": "juiced"},
    {"item": "parsley", "quantity": "1/4", "unit": "cup", "notes": "fresh, chopped"},
    {"item": "red pepper flakes", "quantity": "1/4", "unit": "tsp"},
    {"item": "salt", "quantity": "1", "unit": "tsp"}
  ]'::jsonb,
  '[
    "Cook pasta until al dente, reserve 1 cup pasta water",
    "Melt butter in large skillet over medium heat",
    "Add garlic and red pepper flakes, cook 1 minute",
    "Add shrimp, cook 2 minutes per side until pink",
    "Add wine and lemon juice, simmer 2 minutes",
    "Toss in pasta, add pasta water as needed",
    "Top with parsley, serve immediately"
  ]'::jsonb,
  '{"calories": 540, "protein": 32, "carbs": 58, "fat": 18}'::jsonb,
  '["high-protein"]'::jsonb,
  '["shellfish", "gluten", "dairy"]'::jsonb,
  '["pot", "large-skillet"]'::jsonb,
  '["quick", "elegant", "date-night"]'::jsonb,
  6, 10, 5, 'moderate', 'easy', 'seed'
);

-- Seed substitution rules
INSERT INTO substitution_rules (ingredient_name, substitute_name, dietary_context, cuisine_context, notes, confidence) VALUES
('butter', 'olive oil', 'vegan', 'any', 'Good for sautéing', 9),
('butter', 'coconut oil', 'dairy-free', 'any', 'Best for baking', 8),
('butter', 'vegan butter', 'vegan', 'any', '1:1 replacement', 9),
('milk', 'oat milk', 'vegan', 'any', 'Creamy, good for baking', 8),
('milk', 'almond milk', 'vegan', 'any', 'Light, nutty flavor', 7),
('milk', 'coconut milk', 'vegan', 'asian', 'Rich, works in curries', 9),
('chicken broth', 'vegetable broth', 'vegan', 'any', 'Use in soups and grains', 9),
('honey', 'maple syrup', 'vegan', 'any', '1:1 replacement', 9),
('honey', 'agave nectar', 'vegan', 'any', 'Neutral flavor', 8),
('egg', 'flax egg', 'vegan', 'baking', '1 tbsp flax + 3 tbsp water per egg', 7),
('egg', 'chia egg', 'vegan', 'baking', '1 tbsp chia + 3 tbsp water per egg', 7),
('parmesan', 'nutritional yeast', 'vegan', 'any', 'Cheesy flavor, use generously', 8),
('sour cream', 'greek yogurt', 'vegetarian', 'any', 'Similar tang and creaminess', 9),
('sour cream', 'coconut cream', 'vegan', 'any', 'Rich, works in sauces', 7),
('ground beef', 'ground turkey', 'health-conscious', 'any', 'Leaner, less fat', 8),
('ground beef', 'lentils', 'vegan', 'any', 'Works well in tacos and chili', 7),
('pasta', 'zucchini noodles', 'low-carb', 'any', 'Use a spiralizer', 7),
('rice', 'cauliflower rice', 'low-carb', 'any', 'Pulse in food processor', 8),
('bread crumbs', 'crushed rice crackers', 'gluten-free', 'any', 'For coating', 7),
('soy sauce', 'coconut aminos', 'gluten-free', 'any', 'Less sodium, sweeter', 8);